nautls/nautilus-wallet

public/icons/assets/ermoon.svg

ermoon icon, https://twitter.com/ermoon14

add ermoon icon

---

src/assets/styles/main.css
src/main.ts
src/views/SendView.vue

Add 'Send All' option to 'Send' tab

---

package-lock.json
package.json
src/api/explorer/graphQlService.ts
src/assets/styles/main.css

Retry with alternative instances in case of broadcasting error

---

package-lock.json
package.json
src/background/ergoApiHandlers.ts
src/content-scripts/injector.js
src/types/connector.ts

Allow multiple targets on `get_utxo()` method

---

src/api/explorer/graphQlService.ts

Do not retry transaction broadcasting if "Malformed transaction" error is returned

---

src/api/explorer/graphQlService.ts
src/views/SettingsView.vue

Fix explorer URL validation

---

src/constants/explorer.ts
src/store.ts
src/validators/index.ts
src/validators/url.ts
src/views/ReceiveView.vue
src/views/SendView.vue
src/views/SettingsView.vue

Add custom explorer URL support

---

src/components/ImageSandbox.vue

Add display support for onchan NFT content

---

src/components/AssetInfoModal.vue

Format json NFT description

---

src/api/explorer/graphQlService.ts
src/background/background.ts
src/background/ergoApiHandlers.ts
src/content-scripts/injector.js

dApp Connector: add `get_current_height()`

---

src/views/add/RestoreView.vue

Fix mnemonic words input issues

---

package.json
src/extension/content-scripts/contentScript.ts
src/rpc/protocol.ts

Notify dApps when the bridge script is injected and ready for use

Add `ergo-wallet:injected` event after script injection

---

src/chains/ergo/transaction/prover.ts
src/store.ts

Refactor prover

---

src/views/connector/ConnectionsView.vue

Fix `ConnectorView`

---

src/chains/ergo/services/graphQlService.ts
src/components/StorageRentBox.vue
src/extension/popup/router.ts
src/stores/walletStore.ts
src/types/database.ts

Optimize old UTxOs lookup 

---

package.json
pnpm-lock.yaml
src/components/ExtendedPublicKeyModal.vue
src/composables/index.ts
src/composables/useQRCode.ts
src/stores/assetsStore.ts
src/views/ReceiveView.vue

Replace `qrcode` with `uqr`

---

package.json
src/chains/ergo/services/assetPricingService.ts
src/constants/explorer.ts

Reduce asset price required liquidity and set sigmaspace.io as the default explorer UI

---

src/chains/ergo/addresses.ts

Fix `Empty Array` bug

---

src/stores/walletStore.ts
src/views/TransactionHistory.vue

Polish empty wallet UX

---

src/extension/background/background.ts
src/extension/background/ergoHandlers.ts
src/extension/connector/rpc/protocol.ts

Don't throw if there is no `used` addresses

---

src/i18n/index.ts
src/i18n/locales/fr-FR.json

This translation is made by GPT-4.1 using form the [en-US.json](https://github.com/nautls/nautilus-wallet/blob/master/src/i18n/locales/en-US.json) dictionary

Add French (FR) internationalization

---

src/components/ui/json-viewer/JsonViewer.vue

Dev mode: add JSON transaction copy button
